Update objective-c-xcode.yml

diff --git a/.github/workflows/objective-c-xcode.yml b/.github/workflows/objective-c-xcode.yml
--- a/.github/workflows/objective-c-xcode.yml
+++ b/.github/workflows/objective-c-xcode.yml
@@ -1,65 +1,78 @@
 name: Xcode - Build and Analyze
 
 on:
- push:
-   branches: [ "main" ]
- pull_request:
-   branches: [ "main" ]
+  push:
+    branches: [ "main" ]
+  pull_request:
+    branches: [ "main" ]
 
 jobs:
- build:
-   name: Build and analyse default scheme using xcodebuild command
-   runs-on: macos-latest
+  build:
+    name: Build and analyze default scheme using xcodebuild command
+    runs-on: macos-latest
 
-   steps:
-     - name: Checkout
-       uses: actions/checkout@v4
-     
-     - name: Find Xcode project
-       run: |
-         project_dir=$(find . -name "*.xcodeproj" -type d | head -n 1)
-         if [ -z "$project_dir" ]; then
-           echo "No Xcode project found."
-           exit 1
-         fi
-         echo "Found project: $project_dir"
-         echo "project_dir=$project_dir" >> $GITHUB_ENV
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      
+      - name: Set Environment Variables
+        run: |
+          echo "CODE_SIGN_IDENTITY=" >> $GITHUB_ENV
+          echo "CODE_SIGNING_REQUIRED=NO" >> $GITHUB_ENV
 
-     - name: Set Default Scheme
-       run: |
-         cd $(dirname "$project_dir")
-         scheme_list=$(xcodebuild -list -json -project $(basename "$project_dir") | tr -d "\n")
-         default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-         echo $default | cat >default
-         echo "default_scheme=$default" >> $GITHUB_ENV
-         echo Using default scheme: $default
+      - name: Find Xcode project
+        run: |
+          project_dir=$(find . -name "*.xcodeproj" -type d | head -n 1)
+          if [ -z "$project_dir" ]; then
+            echo "No Xcode project found."
+            exit 1
+          fi
+          echo "Found project: $project_dir"
+          echo "project_dir=$project_dir" >> $GITHUB_ENV
 
-     - name: Build
-       env:
-         scheme: ${{ env.default_scheme }}
-         WORKSPACE_PATH: ${{ github.workspace }}
-       run: |
-         cd $(dirname "$project_dir")
-         xcodebuild clean build \
-           -scheme "$scheme" \
-           -project $(basename "$project_dir") \
-           -destination 'platform=macOS,arch=arm64' \
-           CODE_SIGN_IDENTITY="" \
-           CODE_SIGNING_REQUIRED=NO \
-           SOURCE_ROOT="${WORKSPACE_PATH}/PeteBJJCompFeed/PeteBJJCompFeed" \
-           MOMC_NO_WARN_EMPTY_FILE="" \
-           MOMC_OUTPUT_SUFFIX="" \
-           -verbose
-           
-     - name: Analyze
-       env:
-         scheme: ${{ env.default_scheme }}
-       run: |
-         cd $(dirname "$project_dir")
-         xcodebuild analyze \
-           -scheme "$scheme" \
-           -project $(basename "$project_dir") \
-           -destination 'platform=macOS,arch=arm64' \
-           CODE_SIGN_IDENTITY="" \
-           CODE_SIGNING_REQUIRED=NO \
-           -verbose
+      - name: Set Default Scheme
+        run: |
+          cd $(dirname "$project_dir")
+          scheme_list=$(xcodebuild -list -json -project $(basename "$project_dir"))
+          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['schemes'][0]")
+          if [ -z "$default" ]; then
+            echo "No scheme found."
+            exit 1
+          fi
+          echo $default | cat >default
+          echo "default_scheme=$default" >> $GITHUB_ENV
+          echo Using default scheme: $default
+
+      - name: Clean Derived Data
+        run: |
+          rm -rf ~/Library/Developer/Xcode/DerivedData
+
+      - name: Build
+        env:
+          scheme: ${{ env.default_scheme }}
+          WORKSPACE_PATH: ${{ github.workspace }}
+        run: |
+          cd $(dirname "$project_dir")
+          xcodebuild clean build \
+            -scheme "$scheme" \
+            -project $(basename "$project_dir") \
+            -destination 'platform=macOS,arch=arm64' \
+            CODE_SIGN_IDENTITY="${{ env.CODE_SIGN_IDENTITY }}" \
+            CODE_SIGNING_REQUIRED="${{ env.CODE_SIGNING_REQUIRED }}" \
+            SOURCE_ROOT="${WORKSPACE_PATH}/PeteBJJCompFeed/PeteBJJCompFeed" \
+            MOMC_NO_WARN_EMPTY_FILE="" \
+            MOMC_OUTPUT_SUFFIX="" \
+            -verbose
+            
+      - name: Analyze
+        env:
+          scheme: ${{ env.default_scheme }}
+        run: |
+          cd $(dirname "$project_dir")
+          xcodebuild analyze \
+            -scheme "$scheme" \
+            -project $(basename "$project_dir") \
+            -destination 'platform=macOS,arch=arm64' \
+            CODE_SIGN_IDENTITY="${{ env.CODE_SIGN_IDENTITY }}" \
+            CODE_SIGNING_REQUIRED="${{ env.CODE_SIGNING_REQUIRED }}" \
+            -verbose
